-- MOTO
create table moto (
                      id bigint generated by default as identity primary key,
                      placa varchar(10) not null unique,
                      modelo varchar(50) not null,
                      status varchar(30) not null,
                      setor varchar(50),
                      data_cadastro timestamp,
                      data_atualizacao timestamp
);

-- OCORRENCIA
create table ocorrencia (
                            id bigint generated by default as identity primary key,
                            tipo varchar(30) not null,
                            descricao varchar(255),
                            data date not null,
                            data_registro timestamp,
                            moto_id bigint not null,
                            constraint fk_ocorrencia_moto foreign key (moto_id) references moto(id)
);

-- SECURITY: USERS / ROLES
create table roles (
                       id bigint generated by default as identity primary key,
                       name varchar(50) not null unique
);

create table users (
                       id bigint generated by default as identity primary key,
                       username varchar(50) not null unique,
                       password varchar(200) not null,
                       enabled boolean not null default true
);

create table user_roles (
                            user_id bigint not null,
                            role_id bigint not null,
                            primary key (user_id, role_id),
                            constraint fk_userrole_user foreign key (user_id) references users(id),
                            constraint fk_userrole_role foreign key (role_id) references roles(id)
);
