ALTER SESSION SET CURRENT_SCHEMA = RM554611;

-- Tabela SETOR
CREATE TABLE SETOR (
                       ID          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       NOME        VARCHAR2(100) NOT NULL,
                       DESCRICAO   VARCHAR2(255),
                       CONSTRAINT PK_SETOR PRIMARY KEY (ID)
);

-- Tabela MOTO
CREATE TABLE MOTO (
                      ID           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                      PLACA        VARCHAR2(20) NOT NULL,
                      MODELO       VARCHAR2(100) NOT NULL,
                      STATUS       VARCHAR2(30) NOT NULL,
                      CONSTRAINT PK_MOTO PRIMARY KEY (ID),
                      CONSTRAINT UK_MOTO_PLACA UNIQUE (PLACA)
);

-- Tabela OCORRENCIA
CREATE TABLE OCORRENCIA (
                            ID          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                            MOTO_ID     NUMBER(19) NOT NULL,
                            SETOR_ID    NUMBER(19) NOT NULL,
                            TIPO        VARCHAR2(50) NOT NULL,
                            DESCRICAO   VARCHAR2(4000),
                            DATA_OCOR   DATE NOT NULL,
                            CUSTO       NUMBER(15,2),

                            CONSTRAINT PK_OCORRENCIA PRIMARY KEY (ID),
                            CONSTRAINT FK_OCORRENCIA_MOTO  FOREIGN KEY (MOTO_ID)  REFERENCES MOTO(ID),
                            CONSTRAINT FK_OCORRENCIA_SETOR FOREIGN KEY (SETOR_ID) REFERENCES SETOR(ID)
);

CREATE INDEX IDX_OCORRENCIA_MOTO  ON OCORRENCIA (MOTO_ID);
CREATE INDEX IDX_OCORRENCIA_SETOR ON OCORRENCIA (SETOR_ID);
CREATE INDEX IDX_OCORRENCIA_DATA  ON OCORRENCIA (DATA_OCOR);
